modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="http://creativecommons.org/licenses/by-nc-sa/4.0/"
issueTrackerURL=""
[[mods]] #mandatory
modId="assisted_progression" #mandatory
version="0.9" #mandatory
displayName="Slightly Assisted Progression" #mandatory
authors="khakers" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Mod with various utilities
Modified by khakers, do not report bugs to the original authors
'''
[[dependencies.assisted_progression]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.assisted_progression]]
modId = "forge"
mandatory = true
versionRange = "[40.1.25,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.assisted_progression]]
modId="nucleus_pauljoda"
mandatory=true
versionRange="[2.0,)"
ordering="BEFORE"
side="BOTH"

#[[dependencies.assisted_progression]]
#modId="create"
#mandatory=true
#versionRange="[2.0,)"
#ordering="BEFORE"
#side="BOTH"