modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="assisted_progression" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Assisted Progression" #mandatory
authors="pauljoda" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Mod with various utilities
'''